### ISSUE TITLE
Sms and call log backup

### ISSUE THREAD

**Issue by tsiflimagas** [vmx/sdcontacts#3]
Hi, I'm not sure whether you have any intention or interest in adding the ability to also backup call logs and sms (perhaps your app's name would have to be changed too XD), but I thought to suggest it, although there are similar apps for it, because there's no solution that can back up all three and can do it on a schedule (an opensource one at least).

**Comment by vmx** [comment]
@tsiflimagas thanks for the suggestion. I consider that out of scope for this app. But I'd be happy if someone would fork this repository and create a new app that has those features.
